### ISSUE TITLE
Error: cannot index array with 'api'

### ISSUE THREAD

**Issue by Cochonnes** [ddries/d2c.sh#4]
I am having trouble to set this up. I've cloned the repo, installed it and ran the d2c.sh command. After that, I installed yq. Then I edited the .toml file. But whenever I try to run d2c.sh again, I get the following errors:

Error: cannot index array with 'api' (strconv.ParseInt: parsing "api": invalid syntax)
Error: cannot index array with 'api' (strconv.ParseInt: parsing "api": invalid syntax)
Error: cannot index array with 'dns' (strconv.ParseInt: parsing "dns": invalid syntax)

I am currently running Debian 12 in a container. API and zone key are correctly set.

**Comment by ddries** [comment]
Hello!

That is very strange... Did you install 'yq' from this repo? https://github.com/mikefarah/yq

If you are not sure please uninstall 'yq' and install again from that link

**Comment by Cochonnes** [comment]
My bad, I reinstalled from the linked repo and it's now working. I think I did "apt-get install yq" and called it a day. Still new to Linux. Thanks for the help :)
