### ISSUE TITLE
Only update when IP has changed

### ISSUE THREAD

**Issue by flygpagen** [ddries/d2c.sh#8]
Thanks for an excellent script. There is a guide on [linuxconfig.org](https://linuxconfig.org/automate-dynamic-ip-updates-for-your-domain-with-cloudflare-and-bash-script) describing an update only when the IP has changed, would it be possible to implement this? I prefer your script because it makes it possible to update several records at once.

**Comment by ddries** [comment]
Hello!

Thank you for your interest in d2c.sh! I'm happy that you find it useful! Regarding your issue, the feature you are talking about is already implemented! The script only updates the record when the public IP is indeed different. 

The article you posted is probably inspired in d2c.sh.

Regards!
